### ISSUE TITLE
动漫之家其他问题

### ISSUE THREAD

**Issue by XLOIEUD** [journey3510/10Comic#10]
又来麻烦作者了...＞﹏＜
一、现在下载好像只能下到第一个栏目的内容，第二个下不到欸
![image](https://github.com/journey3510/10Comic/assets/56102571/ddcfa8b2-5e92-41b0-a664-93e6c4604808)

二、勾选全选时会出些问题，现在要先点击a话，然后按全选（无反应），然后取消勾选a话，然后他会自动把除a外其他话全选起来
![image](https://github.com/journey3510/10Comic/assets/56102571/b096a865-fa96-4a7d-84b8-bdcf76f3f39f)

**Comment by XLOIEUD** [comment]
您还在吗？

**Comment by XLOIEUD** [comment]
您好！我衷心地希望您能继续更新您的脚本，如果可以的话，请让我通过支付酬劳的方式继续支持您的工作，可否请您进一步修缮该脚本的一些小瑕疵？如果可以的话，希望您可以留下联系方式，这是我的邮箱：konoxloieud@gmail.com以及我的微信账号：XLOIEUD

**Comment by XLOIEUD** [comment]
您在吗？可以请您给个回复吗？

**Comment by journey3510** [comment]
抱歉。本来打算周末修复好、上传再一并回复的，没有想到。。因为一些事情，拖到了现在。现已经提交了新的版本。

这脚本主要是兴趣和爱好写的，有人点个收藏就足够让我开心了。后面也会继续更新脚本，如果停止更新，会在页面提示的。如有需求可以提，我会考虑的，当然首前提是我能完成。回复的话就不能保证及时的了，更多是想有结果或结论后再一并回复。至于酬劳嘛，说实在的，我也很心动，由兴趣得到的小钱钱，真香~ 如果你真想以这种方式来支持的话，可以留意下你的邮箱

**Comment by XLOIEUD** [comment]
邮箱：konoxloieud@gmail.com
微信：XLOIEUD
QQ：3398707463
您可以添加我的微信，我更加方便与您联络！
