### ISSUE TITLE
下载到指定文件夹

### ISSUE THREAD

**Issue by Z-fly** [journey3510/10Comic#11]
现在下载是下载到默认的文件夹，能否指定到其他地方？或者说创建一个漫画名-章节名的文件夹

**Comment by journey3510** [comment]
> 现在下载是下载到默认的文件夹，能否指定到其他地方？或者说创建一个漫画名-章节名的文件夹

指定其他地方只能到浏览器设置中，修改默认下载目录，但这也会影响其他文件下载路径。<br />
目前下载路径是: 浏览器设置的默认下载目录\10Comic(文件夹)\漫画名(文件夹)\章节名(文件夹)\图。 (保存在多级文件夹中，需要到油猴设置中，下载模式选择 “浏览器API”  <br />
如果需要指定一个文件夹的话，目前只会考虑修改"10Comic"这个文件夹（加进去只是方便测试、删除和区分浏览器下载其他的文件），不会再创建“漫画名-章节名”的文件夹, 我感觉当前的多级目录对有多个漫画和多个章节，比较合理一些。
