### ISSUE TITLE
如果脚本安装在暴力猴上， 疑似在任何地方都找不到下载下来的文件。

### ISSUE THREAD

**Issue by lolisix** [journey3510/10Comic#12]
如果脚本安装在[暴力](https://violentmonkey.github.io/)猴上， 疑似在任何地方都找不到下载下来的文件。 我的浏览器是火狐浏览器， 使用的是暴力猴, 默认下载路径是桌面, 但是桌面上没有任何新的文件夹, 我还进行了全盘扫描, 十分钟内也没找到. 但是用篡改猴就能正常下载.

应该和暴力猴的重要权限里没有下载文件这一项无关. 因为这个脚本在暴力猴里https://greasyfork.org/zh-CN/scripts/435884-wenku-doc-downloader可以正常下载文档.
![](https://s2.loli.net/2023/12/14/tm2sZUqp6y9XdzP.png)

另外, 无论使用篡改猴还是暴力猴, 控制台中都没有任何相关报错.

**Comment by journey3510** [comment]
在火狐浏览器使用暴力猴我也同样无法下载，而在edge浏览器使用却可以下载，但还是有些"异常"，下载图片时没有创建文件夹。<br />
![626499619](https://github.com/journey3510/10Comic/assets/54905059/447d9b03-5e80-46a4-b6bd-d277f53ab052)

暴力猴中我不知道如何让下载的文件有文件夹结构。参考 [链接](https://github.com/violentmonkey/violentmonkey/issues/1349) 
所以目前我不打算寻找\修复这个错误。
