### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by Jiang10086** [journey3510/10Comic#14]
动漫之家无法以压缩包形式下载。以[这部漫画](https://manhua.idmzj.com/qidaozhiguodeliliaier/)为例，显示下载完了却还是没有下载（浏览器也没有弹出下载窗口）。但是在设置里改为直接下载图片就没有问题

**Comment by journey3510** [comment]
我这边测试可以正常下载，没能复现问题，可能无法有效帮助你解决问题。
（一些疑问。其他网站压缩能正常下载吗？有没有使用其他浏览器插件代理下载了？
![image](https://github.com/journey3510/10Comic/assets/54905059/637b5d59-16b4-47c6-8311-4b2bb81ae326)

**Comment by Jiang10086** [comment]
> 我这边测试可以正常下载，没能复现问题，可能无法有效帮助你解决问题。 （一些疑问。其他网站压缩能正常下载吗？有没有使用其他浏览器插件代理下载了？ ![image](https://private-user-images.githubusercontent.com/54905059/324027191-637b5d59-16b4-47c6-8311-4b2bb81ae326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDUwMDYsIm5iZiI6MTcxNDMwNDcwNiwicGF0aCI6Ii81NDkwNTA1OS8zMjQwMjcxOTEtNjM3YjVkNTktMTZiNC00N2M2LTgzMTEtNGIyYmI4MWFlMzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDExNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjU3NDBlNWE1MjE1MWE4YjMwZDQ2ZDUxYzUyOTk4OGUwZmQ0N2E0MGNlMGIyMjU5NmVlM2I4NTlhOGE4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8r5BeCyYh7uYs5X5JIleawoxcwb8EsVh2SPzLAmrYo)

关闭这个issue吧。我现在测试一切正常，但当时就是怎么都下不了压缩包（当时为了排除其他因素还专门开了个浏览器只有油猴一个扩展，也只启用了这个脚本），很迷。
当时其他网站也不能正常下载，没有设置代理。
