### ISSUE TITLE
腾讯漫画无法下载了吗？？

### ISSUE THREAD

**Issue by shijin12** [journey3510/10Comic#7]
大佬，腾讯漫画电脑上能看，但是只能下载封面，后面的内容下载不了了呢

**Comment by journey3510** [comment]
你好，我这边测试是可以下载。
[![tianruo-2023-6-30-638237600761131270.png](https://i.postimg.cc/y8J3Thcg/tianruo-2023-6-30-638237600761131270.png)](https://postimg.cc/QF3M8T6h)
出错有没有可能是下面这种原因，对于付费的章节，如没有提前购买和登录账号，确实是只能下载首张图片的。如果不是，能提供出错的漫画页面吗？我尝试查找下原因？

**Comment by shijin12** [comment]
没付费0.0，我以为是破解可下载呢
