### ISSUE TITLE
腾讯动漫付费漫画下载问题

### ISSUE THREAD

**Issue by XLOIEUD** [journey3510/10Comic#8]
已永久购买且登录，但仍然只能下载付费章节的第一页
![Snipaste_2023-07-02_07-32-25](https://github.com/journey3510/10Comic/assets/56102571/8d36cc4b-8c31-4af8-ae0a-a12afb3457b2)

**Comment by journey3510** [comment]
你好，我这边测试依旧是可以下载的，购买的能完全下载，未购买的一章就只下了一张图片，没有发现什么问题(尴尬.jpg
[![tianruo-2023-7-2-638239328649147303.png](https://i.postimg.cc/bvMr6NTP/tianruo-2023-7-2-638239328649147303.png)](https://postimg.cc/Ny6QFtSC)
想问一些问题，你那已购买的章节能够在原网页上正常阅读吗？下载的是最后一章节吗？看你的图片里最后一章节带有一个 “APP”的图标，但我这边并没有发现有。这网站原在3月起好多漫画都需要app观看，后面又有好多漫画取消app观看了。。参考 https://greasyfork.org/zh-CN/scripts/447819/discussions/171248

**Comment by XLOIEUD** [comment]
您好,作者大大，我购买的漫画是《妖神记》，通过点券的方式购买永久观看，我用于测试的章节上次看到：[441.第261话 白费功夫（下）]（非最后一章仅app观看的）在浏览器中可以正常观看，甚至可以通过其他扒图软件扒出来，所使用脚本也是最新版本，但是在下载时仍然右侧菜单页面仍然显示为红色，下载也只能下载得到本章首页
![image](https://github.com/journey3510/10Comic/assets/56102571/d12de32b-e797-42ef-a48d-397e060e6ea2)
![image](https://github.com/journey3510/10Comic/assets/56102571/fbb919c0-43ef-433c-94a3-e2071db2ec85)
![image](https://github.com/journey3510/10Comic/assets/56102571/5268c693-4c5e-4e10-a191-615a37ce6a06)
![image](https://github.com/journey3510/10Comic/assets/56102571/6a82ba4e-3e04-4ea0-875c-eb316a9d4388)

**Comment by journey3510** [comment]
与章节显示红色无关，直接根据原网页章节是否有付费标志判断的，与b站不同
可以下载，但没有完全获取到所有图片，可能是cookie获取到有问题了
退出登录账号，清除腾迅漫画网站的缓存-参考 https://blog.csdn.net/Ussim/article/details/108377633
重启浏览器，登录账号再试试看？？
——————
如还不行，仍想尝试的话，可以换个浏览器试试看？ 参考 https://greasyfork.org/zh-CN/scripts/447819/discussions/178271 ( 浏览器？？ 一脸蒙逼.jpg

**Comment by XLOIEUD** [comment]
清除cookie，更换浏览器，更换账号，重启账号，把脚本删了再装，都尝试过了，还是没有用欸...

**Comment by journey3510** [comment]
抱歉，我也想不到问题出在哪里了，没折了 ╮(╯-╰)╭
