### ISSUE TITLE
动漫之家下载问题

### ISSUE THREAD

**Issue by XLOIEUD** [journey3510/10Comic#9]
![Snipaste_2023-07-12_21-57-12](https://github.com/journey3510/10Comic/assets/56102571/fa725393-b62a-4ec2-be54-3c8ece355a9a)
![Snipaste_2023-07-12_21-57-05](https://github.com/journey3510/10Comic/assets/56102571/f73c40f1-0e95-42f0-8691-069280fcc3c4)
如图，我记得之前好像也有过这问题...

**Comment by XLOIEUD** [comment]
![image](https://github.com/journey3510/10Comic/assets/56102571/1f147f05-dff9-42d3-93d4-894570ac09ee)
另外，如果用另一个网址下载的话，可以下载到一个22k的空压缩包...

**Comment by XLOIEUD** [comment]
然后我用笔记本试了试，发现manhua.dmzj.com这个网址也可以点击下载按钮，但下完之后是红色的标题，没有压缩包

**Comment by journey3510** [comment]
网站改版了，现在必须要登录才能观看了，新弄的账号，测试你发图片的几个漫画，都是不能观看？ 账号限制了？？就测试了一个能观看到漫画，也能下载了，其它的还是未知。。
[![tianruo-2023-7-14-638249753966273096.png](https://i.postimg.cc/2jJCqxsg/tianruo-2023-7-14-638249753966273096.png)](https://postimg.cc/qg8PS2MG)

关于加载按钮的，如果是开启随网页加载界面的话，可能网页没有加载完，脚本已经运行完了，就会出现这情况。网速卡顿也有会影响，后面可以通过重载列表来获取，算故意留的bug吧。新版本也稍修改了点加载延迟

**Comment by XLOIEUD** [comment]
原本我是随网页打开，然后就没法点击下载按钮，现在改成看到目录页刷出来之后再alt+v手动唤醒可以点击下载按钮了，但是如果是压缩下载则下载到的都是空包，如果是直接下载就啥也没有，测试了几个漫画都一样

**Comment by journey3510** [comment]
更新了新版本，新版本里章节和图片数据改为从 m.dmzj.com 重新获取，原网页显示章节不存在也有可能获取到数据，但在 m.dmzj.com 漫画也下架的话，就没有了

**Comment by XLOIEUD** [comment]
没法做一个适配新版本的或者是适配m.dmzj.com这个站点的10图漫更新吗，麻烦的话我可以支付一些报酬的

**Comment by journey3510** [comment]
新版本已经加上。倒不算麻烦，有用的话，点个收藏就好

**Comment by XLOIEUD** [comment]
今天尝试可以用了，太感谢大佬了，您这样不计回报就要个点赞我都不知道怎么支持您才算好！
